services:
  myportfolio:
    container_name: myportfolio
    build: ./pe-portfolio-site
    restart: always
    env_file:
      - ./pe-portfolio-site/.env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - ./pe-portfolio-site/.env
    volumes:
      - mydatabase:/var/lib/mysql

  shortener:
    container_name: shortener
    build: ./cli_shortener
    restart: always
    env_file:
      - ./cli_shortener/.env

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=traeyoungpointgod@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio
      - shortener

volumes:
  mydatabase:
  nginx_secrets:

